version: '3.5'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./:/app
    env_file:
      - .env
    depends_on:
      - datadog
    environment:
      DD_AGENT_HOST: datadog
    command: sh -c 'npm install && npm run start'

  datadog:
    image: datadog/agent:latest
    environment:
     - DD_API_KEY=${DD_API_KEY}
     - DD_APM_ENABLED=true
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - /proc/:/host/proc:ro
     - /sys/fs/cgroup:/host/sys/fs/cgroup:ro
