version: '3.5'

services:
  app:
    build: .
    restart: always
    tty: true
    stdin_open: true
    command: sh -c "rm -f /app/tmp/pids/server.pid; ./bin/bundle --path vendor/bundle --jobs 4 && ./bin/rails s -p 3000 -b '0.0.0.0'"
    ports:
      - 3000:3000
    environment:
      - RAILS_ENV=development
      - DATABASE_HOST=postgres
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=mypassword
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - ./:/app/
    depends_on:
      - postgres
      - redis

  postgres:
    restart: always
    image: postgres:alpine
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 15432:5432
    environment:
      - POSTGRES_PASSWORD=mypassword

  redis:
    image: redis:alpine
    ports:
      - 6379:6379

volumes:
  ? postgres
